# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

EXPOSE 8080

LABEL io.k8s.description="onbuild child image with update for apche" \
      io.k8s.desplay-name="Apache HTTP Server" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags= "apache, httpd"

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
    sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /ettc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chgrp -R g=u /var/log/httpd /var/run/httpd

USER 1001
